name: Build & Deploy Playwright Image + Tests

on:
  push:
    branches: [main]

jobs:
  build-push-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest

  deploy-tests:
    name: Deploy to Kubernetes
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply K8s Resources
        run: |
          kubectl apply -f k8s/pvc.yaml
          kubectl apply -f k8s/job.yaml

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: |
            tests/test-results
            tests/report.html

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":whale: *Playwright Test Image Deployed & Executed*",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#2eb886' || '#e01e5a' }}",
                  "fields": [
                    { "title": "Status", "value": "${{ job.status }}", "short": true },
                    { "title": "Branch", "value": "${{ github.ref }}", "short": true }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}