apiVersion: batch/v1
kind: CronJob
metadata:
  name: playwright-nightly-tests
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: playwright
              image: mcr.microsoft.com/playwright:v1.43.1-jammy
              workingDir: /tests
              command: ["npx", "playwright", "test"]
              volumeMounts:
                - name: test-files
                  mountPath: /tests
          restartPolicy: Never
          volumes:
            - name: test-files
              persistentVolumeClaim:
                claimName: playwright-test-pvc
