apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playwright-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # Adjust based on your cluster's storage class